Section "Our Yachts"
grizeus/project-YachtRental04 pull request #10
Opened 2024-08-07 22:44 UTC by AnnaBryzghalova

Markup for the "Our Yachts" section.

2024-08-08 11:48 UTC, grizeus requested changes
Fix issues

2024-08-08 11:48 UTC, grizeus commented on src/css/our-yachts.css
1. потрібен ґумовий дизайн між 320 та 375 шириною. у вас він робиться за рахунок тільки правої сторони. а потрібно, щоб він був центрований і гарно виглядав між цими двома значеннями.
2. я так розумію інші картинки Ви в іншому PR будете підключати і мені потрібно тільки мобільну версію відрев'ювити, чи чекати все?

2024-08-08 13:02 UTC, AnnaBryzghalova commented on src/css/our-yachts.css
1. Зроблю
2. Цей PR черновий, він ще не готовий.

2024-08-09 11:41 UTC, grizeus requested changes
Fix issue

2024-08-09 11:41 UTC, grizeus commented on src/css/our-yachts.css
> +    width: 645px;
можливо додати letter-spacing: 0.02em тільки для проміжку між 768 і 1280

2024-08-09 13:46 UTC, grizeus requested changes
Fix issue

2024-08-09 13:46 UTC, grizeus commented on src/css/our-yachts.css
> +    letter-spacing: 0.02em;
я мав на увазі щось типу отакого 
```
@media screen and (min-width: 768px) and (max-width: 1280px) {
  .section-title {  
    letter-spacing: 0.02em;
  }
}
```

2024-08-09 14:29 UTC, grizeus approved these changes
Resolved

2024-08-09 14:30 UTC, merged