transition
grizeus/project-YachtRental04 pull request #13
Opened 2024-08-08 12:16 UTC by id753

transition для кнопок, меню в мобильном, ссылок

2024-08-08 14:51 UTC, grizeus commented on src/css/transition.css
може в один рядок робити замість трьох чи як ви вважаєте?

2024-08-08 16:44 UTC, id753 commented on src/css/transition.css
Как свойства шрифтов записаны в один ряд через font или нет? 
Я считаю так хорошо.

2024-08-09 07:06 UTC, id753 commented on src/css/transition.css
К тому же ментор увидит, что не скопировано с индивидуального проекта свойства с одинаковыми значениями.

2024-08-09 15:18 UTC, grizeus commented on src/css/transition.css
копіювання наше все

2024-08-10 14:34 UTC, id753 commented on src/css/transition.css
На ваше усмотрение. Так лучше думаю.

2024-08-10 16:49 UTC, grizeus requested changes
Remove all commented section

2024-08-11 10:27 UTC, grizeus requested changes
Fix issues

2024-08-11 10:27 UTC, grizeus commented on src/css/footer.css
> +  /* transition: fill 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/footer.css
> +  /* transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/footer.css
> +  /* transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/header.css
> +  /* transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/header.css
> +  /* transition: opacity 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/header.css
> +    /* transition: fill 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/hero.css
> +  /* transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:27 UTC, grizeus commented on src/css/our-yachts.css
> +  /* transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:27 UTC, grizeus commented on src/css/rent.css
> +  /* transition: border 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:27 UTC, grizeus commented on src/css/rent.css
> +  /* transition: font-size 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:27 UTC, grizeus commented on src/css/rent.css
> +  /* transition: border 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:27 UTC, grizeus commented on src/css/rent.css
> +  /* transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1); */
!

2024-08-11 10:27 UTC, grizeus commented on src/css/rent.css
> +  /* transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1),
!

2024-08-11 10:36 UTC, grizeus approved these changes
Resolved

2024-08-11 10:37 UTC, merged