add footer actual width and anchors
grizeus/project-YachtRental04 pull request #14
Opened 2024-08-08 15:32 UTC by ziukoff1985

Вітаю, переробив трохи ширину для всіх break-points та додав анкори на посилання

2024-08-08 17:16 UTC, grizeus reviewed
мабуть позабирайте весь закоментований код

2024-08-08 17:18 UTC, grizeus requested changes

2024-08-08 17:18 UTC, grizeus commented on src/css/footer.css
і що нам дає max-width: none; ? я її видалив і нічого не змінилось, можна її теж прибрати

2024-08-09 08:04 UTC, ziukoff1985 commented on src/css/footer.css
та нічого не дає, експериментував..., зробив коміт де прибрав непотрібні коментарі і max-width: none;

2024-08-09 12:36 UTC, grizeus approved these changes
Resolved

2024-08-09 12:37 UTC, merged