add section "about-us"
grizeus/project-YachtRental04 pull request #15
Opened 2024-08-08 20:23 UTC by YaroslavnaYermolenko

2024-08-08 21:10 UTC, grizeus requested changes
Fix issues

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +  font-family: Inter;
redundant font-family property

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +  background-image: url(../images/about-us/about-us-bg1xmobile.jpg);
wrong path, remove ".." everywhere in path

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +    max-width: 1220px;
max-width: 1280px;

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +    line-height: 23px;
додавайте line-height у відсотках чи одиницях, нехай буде більш консистентний код.

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +  background-color: #0e1823;
background-color вже доданий на всю сторінку, можна видалити

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
> +  letter-spacing: -0.02em;
треба підібрати правильний letter-spacing для різних медіа запитів. десь -0.02em підходить, а десь ні. перегляньте і звіртесь з макетом. наприклад, для планшетної версії непогано його б зробити normal, а потім знову -0.02

2024-08-08 21:10 UTC, grizeus commented on src/partials/about-us.html
> +        <h3 class="about-us-header">
чому це не h2 заголовок?

2024-08-08 21:10 UTC, grizeus commented on src/css/about-us.css
about-us-text-block завузький в 1440 і заширокий в 1280.

2024-08-09 06:01 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
> +  font-family: Inter;
done

2024-08-09 06:01 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
> +  background-image: url(../images/about-us/about-us-bg1xmobile.jpg);
done

2024-08-09 06:01 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
> +    max-width: 1220px;
done

2024-08-09 06:05 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
> +  background-color: #0e1823;
Тут трошки не згодна. У випадку, коли картинка не прогрузиться (хоча навряд таке станеться), колір контейнеру буде білого кольору, як у предка, а має наче бути темного.

2024-08-09 06:06 UTC, YaroslavnaYermolenko commented on src/partials/about-us.html
> +        <h3 class="about-us-header">
згодна

2024-08-09 06:15 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
done

2024-08-09 06:47 UTC, YaroslavnaYermolenko commented on src/css/about-us.css
> +  letter-spacing: -0.02em;
Згідно до макету в моїй секції letter-spacing на всіх версіях -2%. Але, якщо дивитись на зовнішній вигляд текстових полів, то згодна. Підібрала подібне.

2024-08-09 09:10 UTC, grizeus requested changes
Fix issues

2024-08-09 09:10 UTC, grizeus commented on src/css/about-us.css
> +  letter-spacing: -0.02em;
style inspector нас трохи підводить іноді

2024-08-09 09:10 UTC, grizeus commented on src/css/about-us.css
> +  background-image: url(/images/about-us/about-us-bg1xmobile.jpg);
я не зовсім впевнений, що ця картинка повинна бути фоном, а не власне картинкою в html. ще в 1280 правий нижній край не заокруглений по макету. і там присутній якась дивна біла рамка по окружності, може це через фон. зробіть його в html

2024-08-09 17:11 UTC, grizeus approved these changes
Resolved

2024-08-09 17:12 UTC, merged