changed hero.html and hero.css
grizeus/project-YachtRental04 pull request #3
Opened 2024-08-07 03:53 UTC by kris9899

2024-08-07 07:55 UTC, grizeus requested changes

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +    url('path_to_image');
можливо краще зробити це через тег picture в html, Ви таке робили?

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  font-family: 'Inter', sans-serif;
Шрифт в нас однаковий, доданий в common.css, так що font-family можна не вказувати.

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  font-family: 'Inter', sans-serif;
Шрифт в нас однаковий, доданий в common.css, так що font-family можна не вказувати.

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  font-family: 'Inter', sans-serif;
Шрифт в нас однаковий, доданий в common.css, так що font-family можна не вказувати.

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  /* line-height: 18px; */
цей **line-height** з фігми для наглядності, можете його прибрати, щоб код був більш елегантний

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  /* line-height: 14px; */
цей line-height з фігми для наглядності, можете його прибрати, щоб код був більш елегантний

2024-08-07 07:55 UTC, grizeus commented on src/css/hero.css
> +  /* line-height: 32px; */
цей line-height з фігми для наглядності, можете його прибрати, щоб код був більш елегантний

2024-08-07 13:29 UTC, grizeus requested changes
Прочитайте мої пропозиції

2024-08-07 13:29 UTC, grizeus commented on src/css/hero.css
> +  cursor: pointer;
cursor: pointer можливо потрібно на всі кнопки окремо винести

2024-08-07 13:29 UTC, grizeus commented on src/images/dummy.txt
цей файл не потрібно вже додавати

2024-08-07 13:29 UTC, grizeus commented on src/images/background/backgroud-1280-@1x.jpg
назвіть вкладену папку hero, щоб розуміти, що до якої секції відноситься

2024-08-07 13:29 UTC, grizeus commented on src/css/hero.css
> +    url("../images/background/background-mob-@1x.jpg");
пропоную таки додати всі background-images через picture. я допоможу

2024-08-07 15:38 UTC, kris9899 commented on src/images/background/backgroud-1280-@1x.jpg
okay

2024-08-07 15:39 UTC, kris9899 commented on src/css/hero.css
> +    url("../images/background/background-mob-@1x.jpg");
picture,source, srcset в html? ви так хочете,бо в себе в проєкті я реалізовувала саме background через CSS)

2024-08-07 18:29 UTC, grizeus requested changes

2024-08-07 18:29 UTC, grizeus commented on src/css/hero.css
> +    url("../images/background/background-mob-@1x.jpg");
як Вам завгодно

2024-08-07 18:29 UTC, grizeus commented on src/css/hero.css
> +      url(../images/background/background-tab-@1x.jpg);
wrong path to background images

2024-08-07 20:21 UTC, kris9899 commented
Не розумію чому в мене занадто темні background images наче щось іх перекриває(

2024-08-08 08:52 UTC, grizeus commented
> Не розумію чому в мене занадто темні background images наче щось іх перекриває(

Ви експортували тільки зображення? без фону? бо мені вони теж здалися занадто темними

2024-08-08 10:32 UTC, grizeus requested changes
Fix issues

2024-08-08 10:32 UTC, grizeus commented on src/css/common.css
> -  padding-bottom: 80px;
Ви це руками змінювали чи зливали з мейну?

2024-08-08 10:32 UTC, grizeus commented on src/images/hero/backgroud-1280-@1x.jpg
одруківка а назві

2024-08-08 10:32 UTC, grizeus commented on src/images/hero/backgroud-1440_@1x.jpg
одруківка в назві

2024-08-08 10:32 UTC, grizeus commented on src/images/hero/background_1440-@2x.jpg
зробіть після background - а не _

2024-08-08 10:32 UTC, grizeus commented on src/css/hero.css
> +  background-image: linear-gradient(
заберіть linear-gradient з усіх місць, де він є. зображення вже з ним. тому і таке темне стає, якщо ми знову на нього накладаємо цей ефект

2024-08-08 10:32 UTC, grizeus commented on .prettierrc.json
не робіть зміни в файлі, які вже змінені в мейні, бо буде конфлікт. тільки в своїх partials

2024-08-08 15:03 UTC, kris9899 commented on .prettierrc.json
Я вибачаюсь це напевно якось автоматично вийшло тому що я не переходила в даний файл(

2024-08-08 15:04 UTC, kris9899 commented on src/images/hero/background_1440-@2x.jpg
окей

2024-08-08 15:07 UTC, kris9899 commented on src/css/common.css
> -  padding-bottom: 80px;
зливала

2024-08-08 15:07 UTC, kris9899 commented on src/images/hero/backgroud-1280-@1x.jpg
виправляю

2024-08-08 15:08 UTC, kris9899 commented on src/css/hero.css
> +  background-image: linear-gradient(
зараз буду пробувати

2024-08-08 17:52 UTC, grizeus requested changes

2024-08-08 17:52 UTC, grizeus commented on src/css/hero.css
> +      background-image: url("../images/hero/background-1440-@2x.jpg");
ці дві крапки приберіть

2024-08-08 17:58 UTC, grizeus approved these changes
Resolved

2024-08-08 17:59 UTC, merged