add html markup
grizeus/project-YachtRental04 pull request #7
Opened 2024-08-07 16:00 UTC by llizzokk

Зробіла розмітку секції, додала папку для зображень, викачала та оптимізувала всі версії зображень.

2024-08-07 18:41 UTC, grizeus requested changes
замало для PR, додайте хоча б готову мобільну версію

2024-08-08 11:22 UTC, grizeus requested changes

2024-08-08 11:22 UTC, grizeus commented on src/css/advantages.css
повидаляйте зайві стилі, бо це зайве навантаження на браузер. навіщо gap, наприклад, перевизначати кілька разів, якщо він не змінюється.

2024-08-08 12:08 UTC, llizzokk commented on src/css/advantages.css
повидаляла зайве, додала стилі на екрани 1440+

2024-08-08 18:26 UTC, grizeus requested changes
Fix issues

2024-08-08 18:26 UTC, grizeus commented on src/css/advantages.css
> +.adv-container {
та сама проблема з ґумовим дизайном, як у інших.

2024-08-08 20:34 UTC, grizeus approved these changes
Resolved

2024-08-08 20:34 UTC, merged