add header, mobile menu, media
grizeus/project-YachtRental04 pull request #9
Opened 2024-08-07 17:54 UTC by sonja-plgdd

медіа для 1440 додам пізніше

2024-08-07 19:19 UTC, grizeus requested changes

2024-08-07 19:19 UTC, grizeus commented on src/css/header.css
додати падінги до хедеру в режимі меню

2024-08-07 19:19 UTC, grizeus commented on src/css/header.css
> +    font-weight: 500;
add line-height: 121%; виведено експериментальним шляхом

2024-08-07 19:19 UTC, grizeus commented on src/css/header.css
під кнопками навігації забагато місця, через це хедер на 4px вищий ніж потрібно

2024-08-08 08:57 UTC, sonja-plgdd commented on src/css/header.css
пофікшено у новому коміті

2024-08-08 10:54 UTC, grizeus requested changes
fix issues

2024-08-08 10:54 UTC, grizeus commented on src/css/header.css
1. header має бути гумовим між 320 та 375 шириною екрана, а у вас він тягнеться більше за 375.
2. також він тягнеться після досягнення 1280, такого не має бути. встановіть max-width для всіх роздільних здатностей, які ламаються
3. при зменшенні ширини ґумовість у вас досягається лише за рахунок правого краю. зробіть його більш центрованим

2024-08-08 12:35 UTC, sonja-plgdd commented on src/css/header.css
додала новий коміт + додала якірні посилання на секції

2024-08-08 18:07 UTC, sonja-plgdd commented
пофіксила шляхи до іконок та посилання з логотипу

2024-08-08 18:13 UTC, grizeus requested changes
Fix issues

2024-08-08 18:13 UTC, grizeus commented on src/css/header.css
> +    min-width: fit-content;
скоріше за все такий min-width не підходить, треба щоб менше 320px ширина не зменшувалась, а масштабувалась

2024-08-09 12:08 UTC, grizeus approved these changes

2024-08-09 12:08 UTC, merged